version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "exchangelib"
      - dependency-name: "tzlocal"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
