# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.51.0
    hooks:
      - id: terraform_fmt
        name: Run terraform fmt
  - repo: https://github.com/Zac-HD/shed
    rev: 0.4.2
    hooks:
      - id: shed
        name: Run Python linting and fixers
        args: [--refactor, --py39-plus]
        types_or: [python, markdown, rst]
  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.5
    hooks:
      - id: add-msg-issue-prefix
        args: ["--template={}"]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.10
    hooks:
      - id: mdformat
        name: Validate Markdown
        additional_dependencies:
          - mdformat-black
