name: Create Feature Branch List Reconciliation Stack and run Integration Tests
on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  create-feature-branch-list-reconciliation-stack:
    name: Create Feature Branch List Reconciliation Stack
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Python Package
        # TODO this will be remove when using a shared packaging step
        run: |
          python -m pip install --upgrade pipenv
          PATH=$PATH:/opt/github_runner/.local/bin make python-package
      - name: Terraform Format Check
        run: |
          make fmt-check
      - name: Terraform Init
        run: |
          make init
          make workspace env=$(make get-branch-id)
      - name: Terraform Validate
        run: |
          make validate
      - name: Terraform Apply
        run: |
          make apply
      - name: Upload terraform output artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform_outputs
          path: ./terraform_outputs_list-reconciliation.json
          retention-days: 2

  run-integration-tests:
    name: Run Integration Tests
    runs-on: self-hosted
    needs:
      - create-feature-branch-list-reconciliation-stack
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: terraform_outputs
      - name: Assume Role in Dev Account for Integration Tests
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: "arn:aws:iam::092420156801:role/LRTerraformDeploy"
          role-duration-seconds: 1200
      - name: Run Integration tests
        run: |
          # Ensure gpextract and mock_data install location is available to Gauge
          export PATH=$PATH:/opt/github_runner/.local/bin
          make integrationtest-deps
          make integrationtests
      - name: Upload Integration tests result artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_report
          path: test/integrationtests/reports/html-report/*
          retention-days: 2
      - name: Upload Integration tests logs artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: integration_test_logs
          path: test/integrationtests/logs/*
          retention-days: 2
