name: Destroy Environment
on:
  delete:
    branches-ignore:
      - master
      - develop

jobs:
  destroy-list-reconciliation-stack:
    name: Destroy List Reconciliation Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create empty dependency directories
        run: |
          mkdir -p ./build/packages_layer
          mkdir -p ./build/dependencies_layer
      - name: Assume Role in Dev Account
        uses: aws-actions/configure-aws-credentials@v1
        if: github.ref != 'ref/head/master'
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Assume Role in PreProd Account
        uses: aws-actions/configure-aws-credentials@v1
        if: github.ref == 'ref/head/master'
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Init
        run: |
          make init
          make workspace env=$(make get-branch-env branch=${{ github.event.ref }})
      - name: Terraform Destroy
        run: |
          make destroy
      - name: Terraform Delete workspace
        run: |
          make workspace-delete env=$(make get-branch-env branch=${{ github.event.ref }})

  destroy-mesh-stack:
    name: Destroy Mesh Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Assume Role in Dev Account
        uses: aws-actions/configure-aws-credentials@v1
        if: github.ref != 'ref/head/master'
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Assume Role in PreProd Account
        uses: aws-actions/configure-aws-credentials@v1
        if: github.ref == 'ref/head/master'
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Init
        run: |
          make init stack="mesh"
          make workspace stack="mesh" env=$(make get-branch-env branch=${{ github.event.ref }})
      - name: Terraform Destroy
        run: |
          make destroy stack="mesh"
      - name: Terraform Delete workspace
        run: |
          make workspace-delete stack="mesh" env=$(make get-branch-env branch=${{ github.event.ref }})
